name: c_supervisor

description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.27+30
#version: 1.0.23+26
# 1.0.7+10

environment:
    sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # navigation
  # handle svgs
  flutter_svg: ^1.1.6
  http:
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  cached_network_image: ^3.3.0
  vpn_connection_detector: ^1.0.5
  google_maps_flutter: ^2.5.0
  pie_chart: ^5.4.0
  # new_version: ^0.3.0
  new_version_plus:
  provider: ^6.1.1
  device_info_plus: ^9.1.2
  internet_file:
  file_picker:
  dropdown_search: ^5.0.6
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts:
  syncfusion_flutter_gauges:
  pull_to_refresh: ^2.0.0
  dropdown_textfield: ^1.0.8
  googleapis: any
  googleapis_auth: any
  group_radio_button: ^1.3.0

  #injection
#  get_it: ^7.2.0
  # logging Package
#  logger: ^1.1.0

#  flutter_hooks: ^0.18.5+1
  intl: ^0.17.0
#  flutter_screenutil: ^5.6.0

#  camera: 0.10.0+3
  # test screen to suitable with all screen size

#  location: ^4.4.0

#  geolocator: 9.0.0

#  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.0
#  fl_chart: ^0.55.2
  #showToast:
  fluttertoast:


#  pin_code_text_field: ^1.8.0

  url_launcher:
#  geocoding: ^2.1.0
  #local modules

#  networking:
#    path: flutter_network
#
#  flutter_core:
#    path: flutter_core
#  dropdown_button2: ^2.1.4
#  extended_image: ^8.1.0
#  go_router: ^10.1.1
#  get: ^4.6.5
#  talker_dio_logger: ^1.2.2
  expand_widget: ^3.1.1
  expandable: ^5.0.1
  flutter_expandable_fab: ^2.0.0
#  pull_down_button: ^0.9.3
  flutter_staggered_animations: ^1.1.1
#  syncfusion_flutter_charts: ^21.2.4
#  crop_image: ^1.0.11




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
#  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/backgrounds/
    - assets/icons/
    - assets/dashboard/
    - assets/myicons/
    - assets/person.jpg
    - assets/google_cloud_creds/


